language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"


services:
  - cassandra

install:
  - pip install -e .
  - pip install coveralls

# command to run tests
script: nosetests

after_success:
  coveralls