language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  pip install codecov

services:
  - cassandra

install:
  - pip install -e .
  - coverage run setup.py test
  
# command to run tests
script: nosetests

after_success:
  codecov
