language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - pip install codecov
  - pip install coverage
  - pip install pytest-cov

services:
  - cassandra

install:
  - pip install -e .

# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]] ; then coverage run --include='caspanda/*' $(which py.test) ; coverage report; fi


after_success:
  codecov
