language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - pip install codecov
  - pip install coverage
  - pip install pytest-cov

services:
  - cassandra

install:
  - pip install -e .

# command to run tests
script:
  - echo '[pytest]' > pytest.ini
  - echo 'addopts = -vv -r sxX --doctest-modules --doctest-ignore-import-errors --doctest-glob='*.rst' --pyargs blaze docs' >> pytest.ini
  - echo 'norecursedirs = docs/source/scripts' >> pytest.ini
  - coverage run --include='caspanda/*' $(which py.test)


after_success:
  codecov
